修正combine
网络问题，所以多combine做多次失败重试

diff --git a/bin/pig-tools b/bin/pig-tools
--- a/bin/pig-tools
+++ b/bin/pig-tools
@@ -15,7 +15,7 @@ function usage() {
 	echo "usage: --combine (-v -param asdf -param asdf) script.pig"
 }
 
-if [ $? != 0 -o $# = 0 ] ; then usage >&2 ; exit 1 ; fi
+if [ $? != 0 ] ; then usage >&2 ; exit 1 ; fi
 
 function get_pig_script_name(){
 	name=`basename $1 .pig`
@@ -30,15 +30,88 @@ function get_pig_script_name(){
 
 function combine(){
 	echo "================>combine step<=============="
-	$ROOT_PATH/bin/hadoop-tools thfs -get "$COMBINE_REMOTE"
+	re=0
+	echo "get remote "
+	while true
+	do
+		$ROOT_PATH/bin/hadoop-tools --remote fs -get "$COMBINE_REMOTE" "$REMOTE_TMP/$TMP_COMBINE_PATH"
+		if [ $? -ne 0 ]
+		then
+			if [ $re -eq 0 ]
+			then
+				re=1
+				continue
+			else
+				break
+			fi
+		else
+			re=0
+			break
+		fi
+	done
+	if [ $re -ne 0 ]
+	then
+		echo "get remote fail"
+		return $re
+	fi
+
+	echo "download remote "
+	while true
+	do
+		$ROOT_PATH/bin/cluster-tools download "$REMOTE_TMP/$TMP_COMBINE_PATH" "$LOCAL_TMP/"
+		if [ $? -ne 0 ]
+		then
+			if [ $re -eq 0 ]
+			then
+				re=1
+				continue
+			else
+				break
+			fi
+		else
+			re=0
+			break
+		fi
+	done
+	if [ $re -ne 0 ]
+	then
+		echo "download remote fail"
+		return $re
+	fi
+	echo "put local "
+	while true
+	do
+		$ROOT_PATH/bin/hadoop-tools --local fs -put "$LOCAL_TMP/$TMP_COMBINE_PATH" "$COMBINE_REMOTE"
+		if [ $? -ne 0 ]
+		then
+			if [ $re -eq 0 ]
+			then
+				re=1
+				continue
+			else
+				break
+			fi
+		else
+			re=0
+			break
+		fi
+	done
+	if [ $re -ne 0 ]
+	then
+		echo "put local fail"
+		return $re
+	fi
+
 	param=$1" -param COMBINE_LOCAL=$COMBINE_LOCAL -param COMBINE_REMOTE=$COMBINE_REMOTE"
 	pig_play "$COMBINE_SCRIPT" "$param" "$LOCAL_MODE"
 }
 
 function clean_combine(){
-	$ROOT_PATH/bin/hadoop-tools --remote fs -rmr "$COMBINE_REMOTE"
-	$ROOT_PATH/bin/hadoop-tools --local fs -rmr "$COMBINE_REMOTE"
-	$ROOT_PATH/bin/hadoop-tools --local fs -rmr "$COMBINE_LOCAL"
+	$ROOT_PATH/bin/cluster-tools --remote shell "rm -rf $REMOTE_TMP/$TMP_COMBINE_PATH" &
+	$ROOT_PATH/bin/cluster-tools --local shell "rm -rf $LOCAL_TMP/$TMP_COMBINE_PATH" &
+	$ROOT_PATH/bin/hadoop-tools --remote fs -rmr "$COMBINE_REMOTE" &
+	$ROOT_PATH/bin/hadoop-tools --local fs -rmr "$COMBINE_REMOTE" &
+	$ROOT_PATH/bin/hadoop-tools --local fs -rmr "$COMBINE_LOCAL" &
 	wait
 }
 
@@ -69,7 +142,6 @@ combine=
 param=
 export SCRIPT=
 COMBINE_SCRIPT=
-
 md5=`echo $* | md5sum | awk '{print $1}'`
 while [ -n "$*" ]
 do
@@ -93,6 +165,8 @@ do
 		shift ;;
     esac
 done
+
+export TMP_COMBINE_PATH="/"${USER}"_"${PROJECT}"_"${TIMESTAMP}"_"${md5}"_"`get_pig_script_name $SCRIPT`
 #不用存储在永久存储中，直接存储在集群的hdfs即可
 export COMBINE_LOCAL=${LOCAL_HADOOP_TMP}"/"${TMP_COMBINE_PATH}"_"${LOCAL_MODE}
 export COMBINE_REMOTE=${REMOTE_HADOOP_TMP}"/"${TMP_COMBINE_PATH}"_"${REMOTE_MODE}
